# .github/workflows/build-and-push.yml

name: "Build and Push Docker Images"

on:
  push:
    branches:
      - main
    paths:
      - "images/**/Dockerfile"

jobs:
  discover-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.changed-files.outputs.dirs }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get changed Docker image directories"
        id: changed-files
        run: |
          DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'images/.*/Dockerfile$' | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "dirs=${DIRS}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: discover-changes
    if: fromJson(needs.discover-changes.outputs.changed_dirs)[0] != null
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_dir: ${{ fromJson(needs.discover-changes.outputs.changed_dirs) }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push image for ${{ matrix.image_dir }}"
        run: |
          CONTEXT_PATH="${{ matrix.image_dir }}"
          IMAGE_NAME=$(basename "$CONTEXT_PATH")
          DOCKER_HUB_REPO="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}"

          TAG=$(git rev-parse --short HEAD)

          echo "=================================================="
          echo "Building and pushing image: ${DOCKER_HUB_REPO}:${TAG}"
          echo "Context path: ${CONTEXT_PATH}"
          echo "=================================================="

          docker buildx build \
            --push \
            --tag "${DOCKER_HUB_REPO}:${TAG}" \
            --tag "${DOCKER_HUB_REPO}:latest" \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            "${CONTEXT_PATH}"
