name: Build and Push on Dockerfile Change

on:
  push:
    branches:
      - main
    paths:
      - "images/**/Dockerfile"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      services: ${{ steps.list_services.outputs.services }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List services with Dockerfiles
        id: list_services
        run: |
          SERVICES=$(find images -mindepth 2 -maxdepth 2 -type f -name Dockerfile -printf '%h\n' | cut -d'/' -f2 | jq -Rsc 'split("\n") | map(select(length > 0))')
          echo "services=$SERVICES" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare
    if: fromJson(needs.prepare.outputs.services)[0] != null
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        service: ${{ fromJson(needs.prepare.outputs.services) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./images/${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
