# .github/workflows/build-and-push.yml

name: "Build and Push Docker Images"

on:
  push:
    branches:
      - main
    paths:
      - "images/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["placeholder"]

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth:

      - name: "Get changed Dockerfiles"
        id: changed-files
        run: |
          # Compare the current HEAD with the previous commit
          # For pushes to main, this is equivalent to `git diff --name-only HEAD^ HEAD`
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'images/.*/Dockerfile$' | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed_dirs=${CHANGED_DIRS}" >> $GITHUB_OUTPUT

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push changed images"
        run: |
          images='${{ steps.changed-files.outputs.changed_dirs }}'
          for dir in $(echo "$images" | jq -r '.[]'); do
            image_name=$(basename "$dir")
            context_path="$dir"
            
            docker_hub_repo="${{ secrets.DOCKERHUB_USERNAME }}/${image_name}"
            
            tag=$(git rev-parse --short HEAD)
            
            echo "Building and pushing image: ${docker_hub_repo}:${tag}"
            echo "Context path: ${context_path}"
            
            docker buildx build \
              --push \
              --tag "${docker_hub_repo}:${tag}" \
              --tag "${docker_hub_repo}:latest" \
              --cache-from type=gha \
              --cache-to type=gha,mode=max \
              "${context_path}"
          done
